[server]
host = '0.0.0.0'
port = 80
proxy = [
    '127.0.0.1'
] # proxy server ip address
proxy-headers = [
    'X-Forwarded-For',
    'X-Real-IP'
]

[database]
host = '127.0.0.1'
port = 3306
db_name = 'bh_blog'
username = 'root'
password = '12345678'
log_mode = 'silent'

[words-filter]
words-path = ''

[task.cron]
persist-article-read-count = '0 0 0 * * ?'

[log.default]
writer = 'stdout' # stdout or file
encoder = 'console' # console or json
level = 'info'

[log.api]
writer = 'file'
encoder = 'json'
file = './logs/api.log' # only used when type is file or both
level = 'info'

[log.error]
writer = 'file'
encoder = 'console'
file = './logs/api.log'
level = 'info'
