[server]
host = '0.0.0.0'
port = 80
proxy = [
    '127.0.0.1'
] # proxy server ip address
proxy-headers = [
    'X-Forwarded-For',
    'X-Real-IP'
]

[server.jwt]
secret = 'TheJwtSecretShouldBe32Characters'
expire = '2h'
remember-me-expire = '168h' # 7 days
refresh-before-expire = '30m'

[server.csrf]
exclude-patterns = [
    '/account/token'
]

[server.cookie]
domain = ''
path = '/'
secure = false

[database]
host = '127.0.0.1'
port = 3306
db_name = 'bh_blog'
username = 'root'
password = '12345678'
log_mode = 'silent'

[redis]
host = '127.0.0.1'
port = 6379
password = ''

[oss]
endpoint = 'you-endpoint.aliyuncs.com'
access-key-id = 'KeyID'
access-key-secret = 'SecretKey'
bucket-name = 'my-oss-bucket'
save-folder = '/path/to/save/folder'

[mail]
host = 'smtp.example.com'
port = 465
username = 'username'
password = 'password'
from = 'Example<noreply@example.com>'

[mail.template]
path = './conf/mail_template.html'
reply-subject = 'Reply Notification'
review-subject = 'Review Notification'
reply-url-format = 'https://example.com/articles/%d'
review-url = 'https://example.com/admin/comments'
admin-email = 'admin@example.com'

[words-filter]
words-path = '/path/to/words.txt'

[task.cron]
persist-article-read-count = '0 0 0 * * ?'

[log.default]
writer = 'stdout' # stdout or file
encoder = 'console' # console or json
level = 'info'

[log.api]
writer = 'file'
encoder = 'json'
file = './logs/api.log' # only used when type is file or both
level = 'info'

[log.error]
writer = 'file'
encoder = 'console'
file = './logs/api.log'
level = 'info'
